
// Create User
POST http://localhost:2000/users/register
Content-Type: application/json

{
    "first_name": "Bruce",
    "last_name": "Wayne",
    "email": "bruce@gmail.com",
    "password":"Password@123",
    "phone": "087885729863"
}

###
/// Verify User
PATCH http://localhost:2000/users/verified/270c665b-5687-4045-9ca0-8e0748abd001


###
// Register admin
POST http://localhost:2000/admin/add-admin
Content-Type: application/json

{
    "first_name": "Admin",
    "last_name":"Antarisa",
    "email": "antarisaryan@gmail.com",
    "password":"Password@123"
}



###
// Login User
POST http://localhost:2000/users/login
Content-Type: application/json

{
    "email": "ariel@gmail.com",
    "password": "Password@123"
}

###
// Login Admin
POST http://localhost:2000/admin/login
Content-Type: application/json

{
    "email": "antarisaryan@gmail.com",
    "password": "Password@123"
}




###
/// Send reset pass link
POST   http://localhost:2000/users/reset-mail-sent
Content-Type: application/json

{
    "email": "ran@gmail.com"
    }


###
/// Reset Pass
PATCH http://localhost:2000/users/reset-password/dc245116-2922-4311-9116-4da05b712490
Content-Type: application/json

{
    "password":"NewPass@123"
    }

###
/// Get All Users
GET http://localhost:2000/users

###
/// Deactivate user
PATCH http://localhost:2000/admin/user-status/d620e4f5-cd17-4cb8-9cf2-61b539ed15cc

###
/// Get Products by id
GET http://localhost:2000/products/getProductsById/3


# ###
# /// Get A User
# GET http://localhost:5001/users/8006a6c1-4094-4683-8e8b-06b5d78342ec

# ###
# /// Update User
# PATCH  http://localhost:5001/users/8006a6c1-4094-4683-8e8b-06b5d78342ec
# Content-Type: application/json

# {
#     "name": "Antariksa Ryan",
#     "email": "user@gmail.com",
#     "password":"",
#     "confPassword":"",
#     "role": "user"
# }

# ### 
# /// Delete User
# DELETE   http://localhost:5001/users/8006a6c1-4094-4683-8e8b-06b5d78342ec

###
/// Add Product to Cart
POST   http://localhost:2000/cart/add-to-cart
Content-Type: application/json

{
    "product_id": 6,
    "user_id":2,
    "qty":3
    }

###
/// Get cart
GET    http://localhost:2000/cart/cart-item/2

###
/// Update item
PATCH http://localhost:2000/cart/update-cart-item
Content-Type: application/json

{
    "product_id": 17,
    "user_id":2,
    "qty":10
    }

###
/// Delete item
DELETE  http://localhost:2000/cart/delete-cart-item
Content-Type: application/json

{
    "product_id": 7,
    "user_id":2
    }    

###
/// 
POST   http://localhost:2000/cart/check-out-cart
Content-Type: application/json

{
    "user_id":2
    }

###
// Add Address
POST http://localhost:2000/address/add-address
Content-Type: application/json

{
    "name": "Rumah Samarinda",
    "address": "Jl. Pipit No.22 Samarinda Kota",
    "user_id":2
}

###
// Get User Address

GET http://localhost:2000/address/get-address/2

###
// Check Out Cart
POST http://localhost:2000/cart/check-out-cart
Content-Type: application/json

{
    "user_id": 2
}