
// Create User
POST http://localhost:2000/users/register
Content-Type: application/json

{
    "first_name": "Zayn",
    "last_name": "Malik",
    "email": "malik1d@gmail.com",
    "password":"Password@123",
    "phone": "082153460973"
}

###
/// Verify User
PATCH http://localhost:2000/users/verified/270c665b-5687-4045-9ca0-8e0748abd001


###
/// Send reset pass link
POST   http://localhost:2000/users/reset-mail-sent
Content-Type: application/json

{
    "email": "ran@gmail.com"
    }


###
/// Reset Pass
PATCH http://localhost:2000/users/reset-password/dc245116-2922-4311-9116-4da05b712490
Content-Type: application/json

{
    "password":"NewPass@123"
    }




# ###
# /// Get All Users
# GET http://localhost:5001/users

# ###
# /// Get A User
# GET http://localhost:5001/users/8006a6c1-4094-4683-8e8b-06b5d78342ec

# ###
# /// Update User
# PATCH  http://localhost:5001/users/8006a6c1-4094-4683-8e8b-06b5d78342ec
# Content-Type: application/json

# {
#     "name": "Antariksa Ryan",
#     "email": "user@gmail.com",
#     "password":"",
#     "confPassword":"",
#     "role": "user"
# }

# ### 
# /// Delete User
# DELETE   http://localhost:5001/users/8006a6c1-4094-4683-8e8b-06b5d78342ec

